# Generated by Django 4.2.7 on 2023-11-19 19:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_auto_20231119_1559"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="follows",
            field=models.ManyToManyField(
                limit_choices_to={"role": "CREATOR"},
                to=settings.AUTH_USER_MODEL,
                verbose_name="suit",
            ),
        ),
    ]
